name: money_management
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  go_router: ^12.1.1
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  freezed_annotation: ^2.4.1
  freezed: ^2.4.5
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  path_provider: ^2.1.1
  cloud_firestore: ^4.13.3
  image_picker: ^1.0.4
  firebase_storage: ^11.5.3
  google_sign_in: ^6.1.6
  photo_view: ^0.14.0
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  custom_lint: ^0.5.5
  mocktail: ^1.0.1


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/anonymus_avatar.png

