// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:money_management/env.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: ENV.FIREBASE_WEB_API_KEY,
    appId: ENV.FIREBASE_ANDROID_APP_KEY,
    messagingSenderId: '1087034404999',
    projectId: 'flutter-money-management',
    authDomain: 'flutter-money-management.firebaseapp.com',
    storageBucket: 'flutter-money-management.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: ENV.FIREBASE_ANDROID_API_KEY,
    appId: ENV.FIREBASE_ANDROID_APP_KEY,
    messagingSenderId: '1087034404999',
    projectId: 'flutter-money-management',
    storageBucket: 'flutter-money-management.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: ENV.FIREBASE_IOS_API_KEY,
    appId: ENV.FIREBASE_IOS_APP_KEY,
    messagingSenderId: '1087034404999',
    projectId: 'flutter-money-management',
    storageBucket: 'flutter-money-management.appspot.com',
    iosBundleId: 'com.example.moneyManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: ENV.FIREBASE_MACOS_API_KEY,
    appId: ENV.FIREBASE_MACOS_APP_KEY,
    messagingSenderId: '1087034404999',
    projectId: 'flutter-money-management',
    storageBucket: 'flutter-money-management.appspot.com',
    iosBundleId: 'com.example.moneyManagement.RunnerTests',
  );
}
